<?php

namespace ContainerJYcmirx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_ISsV3qSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.ISsV3qS' shared service.
     *
     * @return \App\Controller\EntityManagerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\SecurityController::register()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?');
    }
}
