<?php

namespace ContainerJYcmirx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ContactsController' shared autowired service.
     *
     * @return \App\Controller\ContactsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ContactsController.php';

        $container->services['App\\Controller\\ContactsController'] = $instance = new \App\Controller\ContactsController(($container->privates['App\\Repository\\ContactsRepository'] ?? $container->load('getContactsRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\ContactsController', $container));

        return $instance;
    }
}
