<?php

namespace ContainerAEx1RL6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WX6edlhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WX6edlh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WX6edlh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'accountsRepository' => ['privates', 'App\\Repository\\AccountsRepository', 'getAccountsRepositoryService', true],
        ], [
            'accountsRepository' => 'App\\Repository\\AccountsRepository',
        ]);
    }
}
