<?php

namespace ContainerYcGo8oQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R3NbhXzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R3NbhXz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R3NbhXz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'leadsRepository' => ['privates', 'App\\Repository\\LeadsRepository', 'getLeadsRepositoryService', true],
        ], [
            'leadsRepository' => 'App\\Repository\\LeadsRepository',
        ]);
    }
}
