<?php

namespace Container5ZAXXMF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3A_QSeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3_A.QSe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3_A.QSe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactsRepository' => ['privates', 'App\\Repository\\ContactsRepository', 'getContactsRepositoryService', true],
        ], [
            'contactsRepository' => 'App\\Repository\\ContactsRepository',
        ]);
    }
}
