<?php

namespace ContainerNYXHN8E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfGeneratorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PdfGeneratorController' shared autowired service.
     *
     * @return \App\Controller\PdfGeneratorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PdfGeneratorController.php';

        $container->services['App\\Controller\\PdfGeneratorController'] = $instance = new \App\Controller\PdfGeneratorController(($container->privates['App\\Repository\\AccountsRepository'] ?? $container->load('getAccountsRepositoryService')), ($container->privates['App\\Repository\\ContactsRepository'] ?? $container->load('getContactsRepositoryService')), ($container->privates['App\\Repository\\UsersRepository'] ?? $container->load('getUsersRepositoryService')), ($container->privates['App\\Repository\\PhonesRepository'] ?? $container->load('getPhonesRepositoryService')), ($container->privates['App\\Repository\\EmailsRepository'] ?? $container->load('getEmailsRepositoryService')), ($container->privates['App\\Repository\\LeadsRepository'] ?? $container->load('getLeadsRepositoryService')), ($container->privates['App\\Repository\\OpportunitiesRepository'] ?? $container->load('getOpportunitiesRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\PdfGeneratorController', $container));

        return $instance;
    }
}
