<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErMzbmB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErMzbmB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErMzbmB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErMzbmB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerErMzbmB\App_KernelDevDebugContainer([
    'container.build_hash' => 'ErMzbmB',
    'container.build_id' => '2a08527a',
    'container.build_time' => 1682071730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErMzbmB');
