<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJYcmirx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJYcmirx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJYcmirx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJYcmirx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJYcmirx\App_KernelDevDebugContainer([
    'container.build_hash' => 'JYcmirx',
    'container.build_id' => 'b168d5ef',
    'container.build_time' => 1683554048,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJYcmirx');
