<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAYB5c6T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAYB5c6T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAYB5c6T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAYB5c6T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAYB5c6T\App_KernelDevDebugContainer([
    'container.build_hash' => 'AYB5c6T',
    'container.build_id' => 'ea351250',
    'container.build_time' => 1682067372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAYB5c6T');
